### ISSUE TITLE
Server Error (500) for curl https://www.capesandbox.com/api/tasks/get/iocs/<task-id>/

### ISSUE THREAD

**Issue by certrik** [kevoreilly/CAPEv2#177]
Example:
`
curl https://www.capesandbox.com/api/tasks/get/iocs/1403/
` 
 throws 
`Server Error (500)`

**Comment by doomedraven** [comment]
thanks, i did a quick check, there is some bad data in that report that json/simple_json can't handle, i will try to check that when i will have some free time but that will be a low prior

**Comment by doomedraven** [comment]
ok it should be fixed now for future tasks `ep_bytes` was bytes instead of str and it was giving problem, thanks again for reporting, i will check again tomorrow if that was really solved, on dev server it works now

**Comment by certrik** [comment]
Well that was really fast. Thank you. All the best and stay safe and healthy.

**Comment by doomedraven** [comment]
this was a easy one for my luck :) let us know if you see any other bug or have any feature, thanks the same for you and yours

**Comment by doomedraven** [comment]
ok verified it works https://www.capesandbox.com/api/tasks/get/iocs/1454/

im closing this, but feel free to reach to us if you find any other

**Comment by rikmer** [comment]
https://www.capesandbox.com/api/tasks/get/iocs/1454/ is also working for me but with https://www.capesandbox.com/api/tasks/get/iocs/1612/ , for example, I am still getting the Server Error (500) . Also for 1611 and 1618 .

**Comment by doomedraven** [comment]
when you get that, is due to baddata introduced by something like in that case is
`The string that could not be encoded/decoded was: ��t=��`

when i will have tiem i will check that thanks

**Comment by doomedraven** [comment]
works now
