### ISSUE TITLE
[processing] sqlalchemy.exc.InvalidRequestError: A transaction is already begun on this Session.

### ISSUE THREAD

**Issue by dfr-fands** [kevoreilly/CAPEv2#2187]
On a fresh installation (Ubuntu 22.04) on the latest master branch commit, with default DB settings, the following error occurs when processing any task:

`process.py` ran with the following arguments:
`sudo -u cape /usr/bin/python3 -m poetry run python process.py -d -p7 auto -pt 900`

![image](https://github.com/kevoreilly/CAPEv2/assets/155625068/4538d891-3721-4a2d-a217-5f758e09d234)

I've tried rebooting the server, restarting CAPE, manually clearing the transaction from postgres, but it seems it's happening every time and its not something leftover from a failed analysis or anything like that.

**Comment by doomedraven** [comment]
@tbeadle can you get a look plz?

**Comment by tbeadle** [comment]
This should be fixed with https://github.com/CAPESandbox/community/pull/437. So just update your checkout of the community repo.

**Comment by doomedraven** [comment]
thanks @tbeadle

**Comment by dfr-fands** [comment]
Can confirm its working now, thanks.

**Comment by Yatogaii** [comment]
After applying the updated community repo, it still throws an exception:
![image](https://github.com/user-attachments/assets/a46659ae-562c-4fdf-8930-3a086f59e81e)

Reboot does not help, any ideas?

Thanks

**Comment by doomedraven** [comment]
Restart of service is needed for sure

**Comment by Yatogaii** [comment]
Thank you for your quick reply!

But I'm running process.py by `sudo -u cape poetry run python /opt/CAPEv2/utils/process.py -p6 auto`, so I think there is no `cape-processor.service`.

And `systemctl status cape-processor.service` return not found, maybe it is not a service issue?

**Comment by doomedraven** [comment]
Well if there is no service, then you installed cape in wrong way or installation failed
